### ISSUE TITLE
案例运行出错

### ISSUE THREAD

**Issue by JamesLiAndroid** [wendux/DSBridge-Android#1]
错误日志：
```
01-04 16:19:37.007 3363-3932/wendu.jsbdemo W/System.err: java.lang.IllegalAccessException: Class java.lang.Class<wendu.dsbridge.DWebView$1> cannot access  method void wendu.jsbdemo.JsApi.testAsyn(org.json.JSONObject, wendu.dsbridge.CompletionHandler) of class java.lang.Class<wendu.jsbdemo.JsApi>
01-04 16:19:37.007 3363-3932/wendu.jsbdemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-04 16:19:37.007 3363-3932/wendu.jsbdemo W/System.err:     at wendu.dsbridge.DWebView$1.call(DWebView.java:126)
01-04 16:19:37.007 3363-3932/wendu.jsbdemo W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
01-04 16:19:37.007 3363-3932/wendu.jsbdemo W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
01-04 16:19:37.007 3363-3932/wendu.jsbdemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-04 16:19:37.007 3363-3932/wendu.jsbdemo W/System.err:     at android.os.Looper.loop(Looper.java:148)
01-04 16:19:37.008 3363-3932/wendu.jsbdemo W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
```
然后定位到DWebView下的
` ret = method.invoke(jsb, arg);`
这行代码

机型：一加一代 Android6.0

**Comment by JamesLiAndroid** [comment]
补充：
在点击同步调用和异步调用按钮的时候报错

**Comment by wendux** [comment]
JsApi需要声明为public

**Comment by wendux** [comment]
示例代码已修改。
