### ISSUE TITLE
java.lang.NoSuchMethodError: No super method setFrame(IIII)Z in class Lcom/tencent/tbs/core/webkit/AbsoluteLayout

### ISSUE THREAD

**Issue by joeyzhao1005** [wendux/DSBridge-Android#153]
一加7 pro手机

java.lang.NoSuchMethodError: No super method setFrame(IIII)Z in class Lcom/tencent/tbs/core/webkit/AbsoluteLayout; or its super classes (declaration of 'com.tencent.tbs.core.webkit.AbsoluteLayout' appears in /data/user/0/com.xxx.android/app_tbs/core_share/tbs_jars_fusion_dex.jar)
	at com.tencent.tbs.core.webkit.WebView.access$701(TbsJavaCore:319)
	at com.tencent.tbs.core.webkit.WebView$PrivateAccess.super_setFrame(TbsJavaCore:2195)
	at android.webview.chromium.WebViewChromium.setFrame(TbsJavaCore:1931)
	at com.tencent.tbs.core.webkit.WebView.setFrame(TbsJavaCore:2594)
	at android.view.View.layout(View.java:22082)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22085)
	at android.view.ViewGroup.layout(ViewGroup.java:6290)

**Comment by peter100u** [comment]
我也遇到了，怎么解决呢

**Comment by joeyzhao1005** [comment]
> 我也遇到了，怎么解决呢

没有找到解决办法，好像Android10都有这个问题。如果找到办法，请回复我。

**Comment by shichaohui** [comment]
targetVersion 改成 28 就行了。
[AndroidQ与tencentX5的恩怨情仇](https://sovwcwsfm.com/2019/11/15/AndroidQ%E4%B8%8EtencentX5%E7%9A%84%E6%81%A9%E6%80%A8%E6%83%85%E4%BB%87/#%E5%A4%8D%E7%8E%B0%E6%AD%A5%E9%AA%A4)

**Comment by joeyzhao1005** [comment]
> targetVersion 改成 28 就行了。
> [AndroidQ与tencentX5的恩怨情仇](https://sovwcwsfm.com/2019/11/15/AndroidQ%E4%B8%8EtencentX5%E7%9A%84%E6%81%A9%E6%80%A8%E6%83%85%E4%BB%87/#%E5%A4%8D%E7%8E%B0%E6%AD%A5%E9%AA%A4)

是这样的 我也发现改成28就没问题了 国内的api支持力度真的是滞后严重啊
