### ISSUE TITLE
vivo 手机 5.0 - 5.1 的系统上会崩溃

### ISSUE THREAD

**Issue by xiaoanzi** [wendux/DSBridge-Android#156]
全部集中在手机系统为5.0.2 - 5.1.1，测试机型， vivo X7 、vivo X6 、vivo X6s、 vivo V3.
请问该如何解决？

android.content.res.Resources$NotFoundException: String resource ID #0x2040003
    at android.content.res.Resources.getText(Resources.java:318)
    at android.content.res.VivoResources.getText(VivoResources.java:123)
    at android.content.res.Resources.getString(Resources.java:404)
    at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:694)
    at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:618)
    at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
    at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
    at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
    at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
    at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
    at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
    at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
    at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
    at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
    at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
    at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
    at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
    at android.webkit.WebView.<init>(WebView.java:554)
    at android.webkit.WebView.<init>(WebView.java:489)
    at android.webkit.WebView.<init>(WebView.java:472)
    at android.webkit.WebView.<init>(WebView.java:459)
    at android.webkit.WebView.<init>(WebView.java:449)
    at wendu.dsbridge.DWebView.<init>(DWebView.java:10)
    at com.jeeinc.save.worry.ui.base.BaseWebViewActivity.q(BaseWebViewActivity.kt:8)
    at com.jeeinc.save.worry.ui.base.BaseWebViewActivity.j(BaseWebViewActivity.kt:1)
    at com.jeeinc.save.worry.ui.base.BaseActivity.onCreate(BaseActivity.kt:44)
    at android.app.Activity.performCreate(Activity.java:6083)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
    at android.app.ActivityThread.access$900(ActivityThread.java:175)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5418)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by qingweiSun** [comment]
我也遇到了

**Comment by qingweiSun** [comment]
https://msd.misuland.com/pd/3070888491219950736

**Comment by dudukee** [comment]
```groovy
configurations.all {
        resolutionStrategy {
            // 解决L上WebView崩溃
            force 'androidx.appcompat:appcompat:1.1.0-rc01'
        }
}
```

**Comment by xiaoanzi** [comment]
> ```groovy
> configurations.all {
>         resolutionStrategy {
>             // 解决L上WebView崩溃
>             force 'androidx.appcompat:appcompat:1.1.0-rc01'
>         }
> }
> ```

正解，的确是 androidx.appcompat:appcompat:1.1.0 稳定版的问题。
