### ISSUE TITLE
异步调用时报错

### ISSUE THREAD

**Issue by luqb** [wendux/DSBridge-Android#38]
`W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 3818
W/System.err: java.lang.reflect.InvocationTargetException
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at wendu.dsbridge.DWebView$InnerJavascriptInterface.call(DWebView.java:255)
W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:150)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
W/System.err:     at wendu.dsbridge.DWebView.dispatchStartupQueue(DWebView.java:523)
W/System.err:     at wendu.dsbridge.DWebView.access$800(DWebView.java:53)
W/System.err:     at wendu.dsbridge.DWebView$1.dsinit(DWebView.java:414)
W/System.err: 	... 7 more
D/dsBridge: Call failed：The parameter of "dsinit" in Java is invalid.
`

**Comment by wendux** [comment]
请完善详细的信息：
1.  dsbridge版本和dsbridge.js版本
2. 调用方式
3. 触发问题的方式
请注意格式化代码

**Comment by luqb** [comment]
```
03-25 11:12:14.357 12357-12357/io.dcloud.H5A74CF18 I/art: Rejecting re-init on previously-failed class java.lang.Class<com.just.agentweb.DefaultWebClient$1>
03-25 11:12:14.637 12357-12357/io.dcloud.H5A74CF18 W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 12357
03-25 11:12:15.137 12357-13074/io.dcloud.H5A74CF18 W/System.err: java.lang.reflect.InvocationTargetException
03-25 11:12:15.147 12357-13074/io.dcloud.H5A74CF18 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-25 11:12:15.147 12357-13074/io.dcloud.H5A74CF18 W/System.err:     at wendu.dsbridge.DWebView$InnerJavascriptInterface.call(DWebView.java:255)
03-25 11:12:15.147 12357-13074/io.dcloud.H5A74CF18 W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-25 11:12:15.147 12357-13074/io.dcloud.H5A74CF18 W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
03-25 11:12:15.147 12357-13074/io.dcloud.H5A74CF18 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-25 11:12:15.147 12357-13074/io.dcloud.H5A74CF18 W/System.err:     at android.os.Looper.loop(Looper.java:150)
03-25 11:12:15.147 12357-13074/io.dcloud.H5A74CF18 W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
03-25 11:12:15.147 12357-13074/io.dcloud.H5A74CF18 W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
03-25 11:12:15.147 12357-13074/io.dcloud.H5A74CF18 W/System.err:     at wendu.dsbridge.DWebView.dispatchStartupQueue(DWebView.java:523)
03-25 11:12:15.147 12357-13074/io.dcloud.H5A74CF18 W/System.err:     at wendu.dsbridge.DWebView.access$800(DWebView.java:53)
03-25 11:12:15.147 12357-13074/io.dcloud.H5A74CF18 W/System.err:     at wendu.dsbridge.DWebView$1.dsinit(DWebView.java:414)
03-25 11:12:15.147 12357-13074/io.dcloud.H5A74CF18 W/System.err: 	... 7 more
03-25 11:12:15.147 12357-13074/io.dcloud.H5A74CF18 D/dsBridge: Call failed：The parameter of "dsinit" in Java is invalid.
```
调用方法：
```
 @JavascriptInterface
    public void shareMessage(Object msg,final CompletionHandler<String> handler)
    {
        String url       = "",
               title     = "分享消息的标题",
               content   = "分享消息的文字内容",
               thumb     = Constants.SHARE_ICON,
               logo      = Constants.SHARE_ICON,
               scene     = "WXSceneTimeline";

        if (msg instanceof JSONObject) {
            try {
                JSONObject massage = (JSONObject) msg;
                title = massage.getString("title");
                url   = massage.getString("href");
                if (!TextUtils.isEmpty(massage.getString("content"))) {
                    content = massage.getString("content");
                }
                if (massage.getJSONArray("thumbs")!=null) {

                    thumb = massage.getJSONArray("thumbs").getString(0);
                }

                thumb = TextUtils.isEmpty(thumb) ? logo : thumb;

                String btn = massage.getString("scene");
                scene = TextUtils.isEmpty(btn) ? scene : btn;

            } catch (JSONException e) {
                e.printStackTrace();
            }finally {
                shareMessageCallBack = handler;
            }
}
```
在外部用shareMessageCallBack.complete("1")时就会出现此报错

**Comment by wendux** [comment]
dsbridge和dsbridge. js 版本呢？

**Comment by luqb** [comment]
新写了样本个工程，没有重现，可能时之前的工程里边有其它的代码关联才出的错误
