### ISSUE TITLE
catch exception:java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity

### ISSUE THREAD

**Issue by Colcode** [wendux/DSBridge-Android#71]
at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:354)
        at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
        at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:83)
        at android.support.v7.app.AlertController.installContent(AlertController.java:231)
        at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:278)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:405)
        at android.app.Dialog.show(Dialog.java:304)
        at wendu.dsbridge.DWebView$6.onJsAlert(DWebView.java:695)
        at com.tencent.smtt.sdk.SystemWebChromeClient.onJsAlert(Unknown Source)
        at com.android.webview.chromium.WebViewContentsClientAdapter.handleJsAlert(WebViewContentsClientAdapter.java:380)
        at org.chromium.android_webview.AwContentsClientBridge$$Lambda$2.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6385)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by wendux** [comment]
@Colcode 怎么触发的异常？触发的源码片段和复现步骤贴一下。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Colcode** [comment]
加载H5链接，里面的js有alert弹框，然后就会出现上面的错误。

**Comment by Colcode** [comment]
@wendux 假如加载的URL的js里有open方法，Android 里面没有写对应的方法，有时会崩溃，有时会弹出无该方法的弹框

**Comment by Colcode** [comment]
@wendux  加载的URL的js里有open方法，Android 里面没有写对应的方法，有时崩溃(产生上面的崩溃日志)，不崩溃会弹出无该方法的弹框

**Comment by wendux** [comment]
有两种方法解决这个问题，一个是改一下你应用的主题，第二个是自己实现一下js alert对话框回调，默认的实现用到的dialog 依赖AppCompat系列主题.


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
